name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Xcode ${{ matrix.version }} / ${{ matrix.target }} ${{ matrix.version }}
    runs-on: macos-latest
    strategy:
      matrix:
        version:
          - "26.0.1"
        target:
          - "macOS"
          - "iOS"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.version }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Print Xcode & Swift Version
        run: |
          xcodebuild -version
          swift --version
      - name: Build & Test for ${{ matrix.target }}
        run: |
          if [ "${{ matrix.target }}" == "macOS" ]; then
            swift test -v
          else
            xcodebuild test \
              -scheme AppStoreConnectKit-Package \
              -sdk iphonesimulator \
              -destination "platform=iOS Simulator,name=iPhone 17,OS=26.0.1" \
              CODE_SIGNING_ALLOWED=NO
          fi
      - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
