name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Xcode ${{ matrix.version }} / ${{ matrix.target }} ${{ matrix.version }}
    runs-on: macos-latest
    strategy:
      matrix:
        version:
          - "26.1"
        target:
          - "macOS"
          - "iOS"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.version }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Print Xcode & Swift Version
        run: |
          xcodebuild -version
          swift --version
      - name: Build & Test for ${{ matrix.target }}
        run: |
          if [ "${{ matrix.target }}" == "macOS" ]; then
            swift test -v
          else
            gem install xcpretty --no-document
            xcodebuild test \
              -scheme AppStoreConnectKit-Package \
              -sdk iphonesimulator \
              -destination "platform=iOS Simulator,name=iPhone 17,OS=26.1" \
              -enableCodeCoverage YES \
              CODE_SIGNING_ALLOWED=NO | xcpretty -r junit --output junit.xml
          fi
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.target == 'iOS' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ matrix.target == 'iOS' && !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
